<?php

namespace AppBundle\Repository;

/**
 * Control_SaludRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Control_SaludRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByIdPaciente($idPaciente)
    {
    	$conn = $this->getEntityManager()->getConnection();
		$strQuery = 'SELECT * FROM `control__salud` WHERE `borrado` = 0 AND `id_paciente` = '.$idPaciente;
		$result = $conn->prepare($strQuery);
		$result->execute();
    	return $result->fetchAll();
	}

	public function findAllActive()
    {
    	$conn = $this->getEntityManager()->getConnection();
		$strQuery = 'SELECT * FROM `control__salud` WHERE `borrado` = 0';
		$result = $conn->prepare($strQuery);
		$result->execute();
    	return $result->fetchAll();
	}

	public function graphicsData($idPaciente)
	{
		$conn = $this->getEntityManager()->getConnection();
		$strQuery = "SELECT `fecha`,`peso`,`talla`,`ppc` FROM `control__salud` WHERE `id_paciente` = ? ORDER BY `fecha`";
		$result = $conn->prepare($strQuery);
		$result->execute(array($idPaciente));
		return $result->fetchAll();
	}
}
