<?php

namespace AppBundle\Repository;

/**
 * Datos_DemograficosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Datos_DemograficosRepository extends \Doctrine\ORM\EntityRepository
{
    public function graficoTotalPaciente()
    {
		$conn = $this->getEntityManager()->getConnection();
		$strQuery = "SELECT COUNT(*) AS `cant_Pacientes` FROM `datos__demograficos` WHERE 1 ";
		$result = $conn->prepare($strQuery);
		$result->execute();
    	return $result->fetchAll();
	}

	public function graficoTotalHeladera()
	{
		$conn = $this->getEntityManager()->getConnection();
		$strQuery = "SELECT COUNT(*) AS `heladera` FROM `datos__demograficos` WHERE `heladera` = 1 ";
		$result = $conn->prepare($strQuery);
		$result->execute();
    	return $result->fetchAll();
	}

	public function graficoTotalElectricidad()
	{
		$conn = $this->getEntityManager()->getConnection();
		$strQuery = "SELECT COUNT(*) AS `electricidad` FROM `datos__demograficos` WHERE `electricidad` = 1 ";
		$result = $conn->prepare($strQuery);
		$result->execute();
    	return $result->fetchAll();
	}

	public function graficoTotalMascota()
	{
		$conn = $this->getEntityManager()->getConnection();
		$strQuery = "SELECT COUNT(*) AS `mascotas` FROM `datos__demograficos` WHERE `mascotas` = 1 ";
		$result = $conn->prepare($strQuery);
		$result->execute();
    	return $result->fetchAll();
	}

	public function graficoTipoVivienda()
	{
		$conn = $this->getEntityManager()->getConnection();
		$strQuery = "SELECT `id_vivienda`,COUNT(*) AS `cantidad` FROM `datos__demograficos` GROUP BY `id_vivienda` ";
		$result = $conn->prepare($strQuery);
		$result->execute();
    	return $result->fetchAll();
	}

	public function graficoTipoCalefaccion()
	{
		$conn = $this->getEntityManager()->getConnection();
		$strQuery = "SELECT `id_calefaccion`,COUNT(*) AS `cantidad` FROM `datos__demograficos` GROUP BY `id_calefaccion` ";
		$result = $conn->prepare($strQuery);
		$result->execute();
    	return $result->fetchAll();
	}

	public function graficoTipoAgua()
	{
		$conn = $this->getEntityManager()->getConnection();
		$strQuery = "SELECT `id_agua`,COUNT(*) AS `cantidad` FROM `datos__demograficos` GROUP BY `id_agua` ";
		$result = $conn->prepare($strQuery);
		$result->execute();
    	return $result->fetchAll();
	}
}
