<?php

namespace AppBundle\Repository;

/**
 * HorarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorarioRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTurnos($fecha)
	{
		$conn = $this->getEntityManager()->getConnection();
		$query="SELECT `horario`.`hora` FROM `horario` WHERE `horario`.`hora` NOT IN (SELECT `reserva`.`hora` FROM `reserva` WHERE `fecha`= ?)";
		$result = $conn->prepare($query);
		$result->execute(array($fecha));
		return $result->fetchAll();
	}

	function consultarReserva($fecha,$hora)
	{
		$conn = $this->getEntityManager()->getConnection();
		$query="SELECT * FROM `reserva` WHERE `fecha`=? AND `hora`=?"; // SELECT COUNT(*)
		$result = $conn->prepare($query);
		$result->execute(array($fecha,$hora));
		return $result->rowCount();
	}

	function reservarTurno($fecha,$hora,$dni)
	{
		$conn = $this->getEntityManager()->getConnection();
		$query="INSERT INTO `reserva`(`fecha`,`hora`,`dni`) VALUES(?,?,?)";
		$result = $conn->prepare($query);
		$result->execute(array($fecha,$hora,$dni));
		return $conn->lastInsertId();
	}
}
