<?php

namespace AppBundle\Repository;

/**
 * Obra_SocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Obra_SocialRepository extends \Doctrine\ORM\EntityRepository
{
}
