<?php

namespace AppBundle\Repository;

/**
 * PacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacienteRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllActive()
    {
    	$conn = $this->getEntityManager()->getConnection();
		$strQuery = 'SELECT * FROM `paciente` WHERE `borrado` = 0';
		$result = $conn->prepare($strQuery);
		$result->execute();
    	return $result->fetchAll();
	}

	function obtenerCantidadPacientesActivos(){
		$conn = $this->getEntityManager()->getConnection();
		$strQuery = "SELECT * FROM `paciente` WHERE `borrado` = 0";
		$result = $conn->prepare($strQuery);
		$result->execute();
		return $result->rowCount();
    }

    function obtenerPacientesActivos($primerUsuario, $resultadosporpagina){
    	$conn = $this->getEntityManager()->getConnection();
		$strQuery = "SELECT * FROM `paciente` WHERE `borrado`= 0 LIMIT ".$primerUsuario." , ".$resultadosporpagina;
		$result = $conn->prepare($strQuery);
		$result->execute();
		return $result->fetchAll();
    }
}
