<?php

namespace AppBundle\Repository;

/**
 * Rol_Tiene_PermisoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rol_Tiene_PermisoRepository extends \Doctrine\ORM\EntityRepository
{
}
