<?php

namespace AppBundle\Repository;

/**
 * Tipo_DocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tipo_DocumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
