<?php

namespace AppBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllActive()
    {
    	$conn = $this->getEntityManager()->getConnection();
		$strQuery = 'SELECT * FROM `usuario` WHERE `borrado` = 0';
		$result = $conn->prepare($strQuery);
		$result->execute();
    	return $result->fetchAll();
	}
}
